name: Unity Tester

on: [push, pull_request]

jobs:
  testAllModes:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: game-ci/unity-test-runner@v2.0.0-alpha-7
        id: myTestStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.myTestStep.outputs.artifactsPath }}
 
